spring:
 profiles:
  active: dev
---
server:
 port:8003
spring:
 profiles: dev
 application: 
  name: dept
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8003
    prefer-ip-address: true

info:
  app.name: pf-dept
  company.name: pf.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}