spring:
 profiles:
  active: dev
---
server:
 port: 8003
spring:
 profiles: dev
 application: 
  name: dept
 datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.140:1521:hqoa
    username: hqoac
    password: 1
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.pf.api.dto
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8003
    prefer-ip-address: true

info:
  app.name: pf-dept
  company.name: pf.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}